### ISSUE TITLE
Typo in Docu?

### ISSUE THREAD

**Issue by D-MBLD** [SAP/cloud-s4-sdk-pipeline#18]
What does default value 1C in forkCount Parameter of integrationTests mean?
(File https://github.com/SAP/cloud-s4-sdk-pipeline/blob/master/configuration.md)
Typo?

**Comment by daniel-kurzynski** [comment]
The `forkCount` parameter is passed to the surefire test execution. 

The meaning of C is explained in the surefire documentation for `forkCount`:
```
Option to specify the number of VMs to fork in parallel in order to execute the tests. When terminated with "C", the number part is multiplied with the number of CPU cores. Floating point value are only accepted together with "C". If set to "0", no VM is forked and all tests are executed within the main process.
```
https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#forkCount
