### ISSUE TITLE
How to specify Maven repository in mtaBuild step?

### ISSUE THREAD

**Issue by Wesley-Qi** [SAP/cloud-s4-sdk-pipeline#21]
Hi colleagues,

I have a question regarding our pipeline setting. 

We configured 'mavenExecute' and 'mtaBuild' steps. In 'mavenExecute', we specified a prepared settings.xml by relative path, in it we specified nexus servers as Maven repositories. However, during build, it's found that the mtaBuild didn't download dependencies from Maven repositories specified in settings.xml, but tried to download from: 'https://repo.maven.apache.org/maven2', and therefore many dependencies are missed and mtaBuild failed.

Why mtaBuild didn't share configurations of settings.xml? Does mtaBuild have its own repo configuration?

Below are related settings in pipeline_config:
steps:
  mavenExecute:
    dockerImage: maven:3.5-jdk-8-alpine
    projectSettingsFile: './settings.xml'
  mtaBuild:
    dockerImage: 'ppiper/mta-archive-builder'

Below is part of console logs of the failed job:
```
Log entry has been removed due to sensitive information
```

Can you help give some advice?

If any info is required, just let me know.

Thanks so much!

Best,
Terry

**Comment by fgeckeler** [comment]
Hi Terry,

thank you for reporting that issue and we have to enhance our conifguration.md to make that more clear.
To use your configured maven repo URL in the mtaBuild step is possible if you configure it in this step.
Example:
```yaml
steps:
  mtaBuild:
    projectSettingsFile: 'my-repo'
```

For more information please visit the documentation of the mtaBuild step which you can find here: https://sap.github.io/jenkins-library/steps/mtaBuild/

Best regards
Florian
