### ISSUE TITLE
Skipping stage

### ISSUE THREAD

**Issue by bullrox** [SAP/cloud-s4-sdk-pipeline#23]
as I can see the conditional checks if the stage will be executed:

![image](https://user-images.githubusercontent.com/38818832/69140033-fbf00b00-0ac1-11ea-8e1a-a3273e42e26f.png)

Is there a setting which can be used for skipping a certain stage (For example in the pipeline_config.yml)?

**Comment by fwilhe** [comment]
Hi @bullrox,

can you elaborate a little more on your concrete requirement? I might be able to provide you a better answer depending on what you're trying to achieve.

Which stage would you like to enable/disable in which conditions (and why)?

In _general_, you can inspect how it is decided if a stage is run in [`initStageSkipConfiguration`](https://github.com/SAP/cloud-s4-sdk-pipeline-lib/blob/master/vars/initStageSkipConfiguration.groovy).

Kind regards

Florian

**Comment by bullrox** [comment]
Hi @fwilhe ,

I would like to skip the 'Quality Checks' stage as it throws a Connection Timeout Exception which causes an unstable pipeline run.

![image](https://user-images.githubusercontent.com/38818832/69145037-006df100-0acd-11ea-8441-cdade0b016ab.png)

Thus I am wondering if I can configure 'pipeline_config.yml' or any other config file in a way to skip the execution of certain pipeline stages.

**Comment by fwilhe** [comment]
Hi @bullrox, I'm not aware of any issues with api.sap.com as of now. Do you observe this issue longer?

We don't have an option to skip the quality checks of the pipeline as we consider them to be important. I understand that it is bad if the pipeline fails because of availability issues, but my guess would be that it should work if you retry. At least my quick check showed that api.sap.com responds as desired.

**Comment by fwilhe** [comment]
Hi @bullrox, do you still experience issues with that matter?

**Comment by daniel-kurzynski** [comment]
With the latest release you can either skip individual quality checks or use extensibility to configure which stages should be executed: https://sap.github.io/jenkins-library/extensibility/
