### ISSUE TITLE
Docker repo credentials are not picked by pipeline

### ISSUE THREAD

**Issue by T1mey** [SAP/cloud-s4-sdk-pipeline#27]
As we're pulling the docker images from an internal artifactory we need to pull with credentials.
In the MB pipeline we set a repo URL and left the label empty under config "Pipeline Model Definition".

This config has no effect on the pipeline. It falls back to https://registry-1.docker.io/v2/

Or is there another way to connect to docker repo with credentials ?

**Comment by daniel-kurzynski** [comment]
Do you want to pull all docker images from that repostiory?

If yes, modifying your Jenkinsfile in the following way could help:

```
String pipelineVersion = "master"

node {
    deleteDir()
    sh "git clone --depth 1 https://github.com/SAP/cloud-s4-sdk-pipeline.git -b ${pipelineVersion} pipelines"
    docker.withRegistry('https://registry.example.com', 'credentials-id') {
        load './pipelines/s4sdk-pipeline.groovy'
    }
}
```

**Comment by T1mey** [comment]
Thanks a lot for helping out ... that did it ;-)
