### ISSUE TITLE
Config schema validation warnings not up to date

### ISSUE THREAD

**Issue by hapreanmanuel** [SAP/cloud-s4-sdk-pipeline#35]
Hello developers,

I see two warning messages in the Config schema validation warnings panel in Jenkins

## Issue Description
![image](https://user-images.githubusercontent.com/18533449/81149386-c8793e00-8f86-11ea-9e94-1040d2d8c4bb.png)
The warnings displayed after the deployment seem to be outdated.
From the documentation of pipeline v32. the artifactDeployment.nexus now has 'mavenRepository' and 'npmRepository' instead of 'repository' property.
![image](https://user-images.githubusercontent.com/18533449/81149896-bea40a80-8f87-11ea-8f9c-50181c926fd9.png)

A similar situation is happening for lint.ui5BestPractices where we use the new flag instead of the deprecated one
![image](https://user-images.githubusercontent.com/18533449/81149846-a7651d00-8f87-11ea-8105-610a332c1b4b.png)

The pipeline is not failing, but the schema validation warnings are faulty

## Search for existing solution beforehand

* I searched for a similar GitHub issue before and found none
* I checked the [pipeline configuration docs](https://github.com/SAP/cloud-s4-sdk-pipeline/blob/master/configuration.md) and [the general pipeline docs](https://github.com/SAP/cloud-s4-sdk-pipeline/tree/master/doc/pipeline) for an answer of my issue

* Project type, for example:
    * SDK Maven Archetype scp-cf-spring

I assume the config schema validation team is already working on keeping up with the pipeline releases, but I still tought it might be helpful to report this issue here.

Kind Regards,
Manu

**Comment by fwilhe** [comment]
Hi @hapreanmanuel 

Thanks for the heads up. I've opened a PR in the schema store to update the pipeline. This should not have happened.

Kind regards,

Florian

**Comment by fwilhe** [comment]
Should be resolved
