### ISSUE TITLE
stageInitS4sdkPipeline running on slave node not working any more

### ISSUE THREAD

**Issue by ORASTARK** [SAP/cloud-s4-sdk-pipeline#36]
I used to overwrite following node with slave node label to for this stage running in slave node, but it will fail all the time and change back to master node. 
[Pre-condition]
1. My master node does not have web access to github,com, only my slave nodes have
2. My first slave node label is marked as 'slave1' for demo purpose.

[worked solution previously]
Modification in stageInitS4sdkPipeline.groovy
node('slave1') {
        deleteDir()
        checkoutAndInitLibrary(script: script, customDefaults: parameters.customDefaults)
...

[Current Error message] showing when running initS4sdkPipeline, it is changed back to master node.
[Pipeline] echo
10:24:37  [artifactSetVersion] Sending telemetry data is disabled.
[Pipeline] node
10:24:38  Running on Jenkins in /var/jenkins_home/workspace/PipelineJava_master
[Pipeline] {
[Pipeline] }
[Pipeline] // node
[Pipeline] echo
10:24:38  --- Begin library step of: mavenExecute ---
[Pipeline] echo
10:24:38  Unstash content: piper-bin
[Pipeline] unstash
[Pipeline] echo
10:24:38  Unstash failed: piper-bin (No such saved stash ‘piper-bin’)
[Pipeline] httpRequest
10:24:38  HttpMethod: GET
10:24:38  URL: https://github.com/SAP/jenkins-library/releases/download/v1.39.0/piper
10:24:38  Sending request to url: https://github.com/SAP/jenkins-library/releases/download/v1.39.0/piper
10:24:38  Treating UnknownHostException(github.com: Name or service not known) as 404 Not Found

**Comment by daniel-kurzynski** [comment]
Issue was fixed by reverting to curl.
