### ISSUE TITLE
Is there any time table to support new CAP project generated by Business Application Studio?

### ISSUE THREAD

**Issue by ORASTARK** [SAP/cloud-s4-sdk-pipeline#38]
## Issue Description (Mandatory)

The pipeline is failing in the stage: Build

MTA command cannot be found.

## Log Output (Mandatory)

```
PLEASE PASTE YOUR LOG HERE WITHIN THE BACKTICKS
```

## Link to Jenkins Job (if it can be shared)

PLEASE PLACE THE LINK HERE

## Reproduce the Issue Locally (Mandatory)

In case a maven/npm command or similar failed:
* [ ] I tried to reproduce the issue locally
* [ ] I could reproduce the issue locally

## Search for existing solution beforehand (Mandatory)

* [X] I searched for an existing solution on [StackOverflow](https://stackoverflow.com/questions/tagged/sap-cloud-sdk) and my question was not answered there
* [X] I searched for a similar GitHub issue before and found none
* [X] I checked the [pipeline configuration docs](https://github.com/SAP/cloud-s4-sdk-pipeline/blob/master/configuration.md) and [the general pipeline docs](https://github.com/SAP/cloud-s4-sdk-pipeline/tree/master/doc/pipeline) for an answer of my issue

***Please try the GitHub search, it works really well***

## Project Details (Mandatory)

* Link to GitHub repo: PLACE YOUR LINK HERE
* Project type, for example:
    * [ ] SDK Maven Archetype
    * [X] MTA (which types of modules?)
    * [ ] JavaScript
    * [ ] None of the above (unsupported)

**Comment by fwilhe** [comment]
Hi @ORASTARK 

those projects are supported. There must be something with the configuration. Please provide more context about the log, the project layout and the pipeline configuration. If you create a new project from Business Application Studio. Please see _Unit 4: Continuous Integration (CI) and Continuous Delivery (CD)_ of the _Building Applications with SAP Cloud Application Programming Model_ course on openSAP for an intro on the topic: https://open.sap.com/courses/cp7/items/36pMNe2zf6SCrz67GXrZo3

If that does not help, please provide more info as mentioned above.

Best,

Florian
