### ISSUE TITLE
Pipeline Support for new CAP template project in Business Application Studio

### ISSUE THREAD

**Issue by ORASTARK** [SAP/cloud-s4-sdk-pipeline#40]
## Issue Description (Mandatory)

The pipeline is failing in the stage: stage 'Build and Test'
PLEASE PLACE YOUR DESCRIPTION HERE

## Log Output (Mandatory)

```
PLEASE PASTE YOUR LOG HERE WITHIN THE BACKTICKS
```

## Link to Jenkins Job (if it can be shared)

PLEASE PLACE THE LINK HERE

## Reproduce the Issue Locally (Mandatory)

In case a maven/npm command or similar failed:
* [X ] I tried to reproduce the issue locally
* [X ] I could reproduce the issue locally

## Search for existing solution beforehand (Mandatory)

* [X ] I searched for an existing solution on [StackOverflow](https://stackoverflow.com/questions/tagged/sap-cloud-sdk) and my question was not answered there
* [X ] I searched for a similar GitHub issue before and found none
* [X ] I checked the [pipeline configuration docs](https://github.com/SAP/cloud-s4-sdk-pipeline/blob/master/configuration.md) and [the general pipeline docs](https://github.com/SAP/cloud-s4-sdk-pipeline/tree/master/doc/pipeline) for an answer of my issue

***Please try the GitHub search, it works really well***

## Project Details (Mandatory)

* Link to GitHub repo: PLACE YOUR LINK HERE
* Project type, for example:
    * [ ] SDK Maven Archetype
    * [ ] MTA (which types of modules?)
    * [ ] JavaScript
    * [ ] None of the above (unsupported)

**Comment by ORASTARK** [comment]
Downloaded from central: https://repo.maven.apache.org/maven2/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.3/org.eclipse.sisu.inject-0.3.3.jar (379 kB at 953 kB/s)
15:30:04  info  mtaBuild - Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar (480 kB at 1.2 MB/s)
15:30:04  info  mtaBuild - [INFO] Installing node version v12.16.1
15:30:04  info  mtaBuild - [INFO] Downloading https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.gz to /root/.m2/repository/com/github/eirslett/node/12.16.1/node-12.16.1-linux-x64.tar.gz
15:30:04  info  mtaBuild - [INFO] No proxies configured
15:30:04  info  mtaBuild - [INFO] No proxy was configured, downloading directly
15:30:05  info  mtaBuild - [INFO] Unpacking /root/.m2/repository/com/github/eirslett/node/12.16.1/node-12.16.1-linux-x64.tar.gz into /var/jenkins/workspace/PipelineCAP4Java_master@2/srv/node/tmp
15:30:06  info  mtaBuild - .[INFO] Copying node binary from /var/jenkins/workspace/PipelineCAP4Java_master@2/srv/node/tmp/node-v12.16.1-linux-x64/bin/node to /var/jenkins/workspace/PipelineCAP4Java_master@2/srv/node/node
15:30:07  info  mtaBuild - .[INFO] Extracting NPM
15:30:07  info  mtaBuild - [INFO] Installed node locally.
15:30:07  info  mtaBuild - [INFO] 
15:30:07  info  mtaBuild - [INFO] --- frontend-maven-plugin:1.10.0:npm (npm install) @ PipelineCAP4Java ---
15:30:07  info  mtaBuild - [INFO] Running 'npm install' in /var/jenkins/workspace/PipelineCAP4Java_master@2/srv
15:30:08  info  mtaBuild - .[INFO] audited 105 packages in 0.836s
15:30:08  info  mtaBuild - [INFO] 
15:30:08  info  mtaBuild - [INFO] 1 package is looking for funding
15:30:08  info  mtaBuild - [INFO]   run `npm fund` for details
15:30:08  info  mtaBuild - [INFO] 
15:30:08  info  mtaBuild - [INFO] found 0 vulnerabilities
15:30:08  info  mtaBuild - [INFO] 
15:30:08  info  mtaBuild - [INFO] 
15:30:08  info  mtaBuild - [INFO] --- frontend-maven-plugin:1.10.0:npm (cds build) @ PipelineCAP4Java ---
15:30:08  info  mtaBuild - [INFO] Running 'npm run build' in /var/jenkins/workspace/PipelineCAP4Java_master@2/srv
15:30:08  info  mtaBuild - [INFO] 
15:30:08  info  mtaBuild - [INFO] > PipelineCAP4Java@1.0.0 build /var/jenkins/workspace/PipelineCAP4Java_master@2
15:30:08  info  mtaBuild - [INFO] > cds build/all --clean
15:30:08  info  mtaBuild - [INFO] 
15:30:09  info  mtaBuild - [INFO] [cds] - Determining CDS build tasks from CDS configuration - applying defaults
15:30:09  info  mtaBuild - [INFO] [cds] - Determining implementation technology
15:30:09  info  mtaBuild - [INFO] [cds] - Found implementation technology java
15:30:09  info  mtaBuild - [INFO] [cds] - Determining fiori modules - matching modules */webapp/manifest.json
15:30:09  info  mtaBuild - [INFO] [cds] - Found fiori app paths []
15:30:09  info  mtaBuild - [INFO] [cds] - No CDS custom build tasks defined for project [/var/jenkins/workspace/PipelineCAP4Java_master@2].
15:30:09  info  mtaBuild - [INFO] [cds] - The following build tasks have been auto-created and will be executed.
15:30:09  info  mtaBuild - [INFO] [cds] - You may want to add them to .cdsrc.json or package.json of your project and customize to your needs if required.
15:30:09  info  mtaBuild - [INFO] {
15:30:09  info  mtaBuild - [INFO]   "build": {
15:30:09  info  mtaBuild - [INFO]     "target": ".",
15:30:09  info  mtaBuild - [INFO]     "tasks": [
15:30:09  info  mtaBuild - [INFO]       {"src":"srv","for":"java-cf","options":{"model":["srv"]}}
15:30:09  info  mtaBuild - [INFO]     ]
15:30:09  info  mtaBuild - [INFO]   }
15:30:09  info  mtaBuild - [INFO] }
15:30:09  info  mtaBuild - [INFO] 
15:30:09  info  mtaBuild - [INFO] [cds] - building project [/var/jenkins/workspace/PipelineCAP4Java_master@2], clean [true]
15:30:09  info  mtaBuild - [INFO] 
15:30:09  info  mtaBuild - [INFO] [cds] - cds [3.34.2], compiler [1.26.2], home. [/var/jenkins/workspace/PipelineCAP4Java_master@2/node_modules/@sap/cds]
15:30:09  info  mtaBuild - [INFO] 
15:30:09  info  mtaBuild - [INFO] [cds] - building module [srv] using [Java CF Module Builder]
15:30:09  info  mtaBuild - [INFO] [cds] - no model found, skip build
15:30:09  info  mtaBuild - [INFO] 
15:30:09  info  mtaBuild - [INFO] cds build completed in: 9.633ms
15:30:09  info  mtaBuild - [INFO] 
15:30:09  info  mtaBuild - [INFO] 
15:30:09  info  mtaBuild - [INFO] --- frontend-maven-plugin:1.10.0:npm (cds schema) @ PipelineCAP4Java ---
15:30:09  info  mtaBuild - [INFO] Running 'npm run schema' in /var/jenkins/workspace/PipelineCAP4Java_master@2/srv
15:30:09  info  mtaBuild - [INFO] 
15:30:09  info  mtaBuild - [INFO] > PipelineCAP4Java@1.0.0 schema /var/jenkins/workspace/PipelineCAP4Java_master@2
15:30:09  info  mtaBuild - [INFO] > cds compile srv --to sql > srv/src/main/resources/schema.sql
15:30:09  info  mtaBuild - [INFO] 
15:30:09  error mtaBuild - [INFO] [ERROR] Couldn't find a CDS model for: srv in: /var/jenkins/workspace/PipelineCAP4Java_master@2
15:30:09  info  mtaBuild - [INFO]     at cds.load (/var/jenkins/workspace/PipelineCAP4Java_master@2/node_modules/@sap/cds/lib/models/load.js:15:39)
15:30:09  info  mtaBuild - [INFO]     at Object.compile (/var/jenkins/workspace/PipelineCAP4Java_master@2/node_modules/@sap/cds/bin/compile.js:134:17)
15:30:09  info  mtaBuild - [INFO]     at Module.exports (/var/jenkins/workspace/PipelineCAP4Java_master@2/node_modules/@sap/cds/bin/cds.js:44:23)
15:30:09  info  mtaBuild - [INFO]     at Object.<anonymous> (/var/jenkins/workspace/PipelineCAP4Java_master@2/node_modules/@sap/cds/bin/cds.js:133:29)
15:30:09  info  mtaBuild - [INFO]     at Module._compile (internal/modules/cjs/loader.js:1158:30)
15:30:09  info  mtaBuild - [INFO]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
15:30:09  info  mtaBuild - [INFO]     at Module.load (internal/modules/cjs/loader.js:1002:32)
15:30:09  info  mtaBuild - [INFO]     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
15:30:09  info  mtaBuild - [INFO]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
15:30:09  info  mtaBuild - [INFO]     at internal/main/run_main_module.js:18:47
15:30:09  error mtaBuild - [INFO] npm ERR! code ELIFECYCLE
15:30:09  error mtaBuild - [INFO] npm ERR! errno 1
15:30:09  error mtaBuild - [INFO] npm ERR! PipelineCAP4Java@1.0.0 schema: `cds compile srv --to sql > srv/src/main/resources/schema.sql`
15:30:09  error mtaBuild - [INFO] npm ERR! Exit status 1
15:30:09  error mtaBuild - [INFO] npm ERR! 
15:30:09  error mtaBuild - [INFO] npm ERR! Failed at the PipelineCAP4Java@1.0.0 schema script.
15:30:09  error mtaBuild - [INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
15:30:09  info  mtaBuild - [INFO] 
15:30:09  error mtaBuild - [INFO] npm ERR! A complete log of this run can be found in:
15:30:09  error mtaBuild - [INFO] npm ERR!     /home/mta/.npm/_logs/2020-06-29T07_30_09_243Z-debug.log
15:30:09  info  mtaBuild - [INFO] ------------------------------------------------------------------------
15:30:09  info  mtaBuild - [INFO] BUILD FAILURE
15:30:09  info  mtaBuild - [INFO] ------------------------------------------------------------------------
15:30:09  info  mtaBuild - [INFO] Total time:  22.006 s
15:30:09  info  mtaBuild - [INFO] Finished at: 2020-06-29T07:30:09Z
15:30:09  info  mtaBuild - [INFO] ------------------------------------------------------------------------
15:30:09  error mtaBuild - [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.10.0:npm (cds schema) on project PipelineCAP4Java: Failed to run task: 'npm run schema' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
15:30:09  error mtaBuild - [ERROR] 
15:30:09  error mtaBuild - [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
15:30:09  error mtaBuild - [ERROR] Re-run Maven using the -X switch to enable full debug logging.
15:30:09  error mtaBuild - [ERROR] 
15:30:09  error mtaBuild - [ERROR] For more information about the errors and possible solutions, please read the following articles:
15:30:09  error mtaBuild - [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
15:30:09  error mtaBuild - [2020-06-29 07:30:09] ERROR could not build the "PipelineCAP4Java-srv" module: could not execute the "mvn clean package" command: exit status 1
15:30:09  info  mtaBuild - make: *** [Makefile_20200629072938.mta:37: PipelineCAP4Java-srv] Error 1
15:30:09  info  mtaBuild - Error: could not build the MTA project: could not execute the "make -f Makefile_20200629072938.mta p=CF mtar=PipelineCAP4Java.mtar strict=true mode= t=\"./\"" command: exit status 2
15:30:09  fatal mtaBuild - failed to execute mta build - running command 'mbt' failed: cmd.Run() failed: exit status 1

**Comment by daniel-kurzynski** [comment]
The error message "Couldn't find a CDS model for: srv in: /var/jenkins/workspace/PipelineCAP4Java_master@2" more looks like a CAP/project specific issue. 
Have you verified that you can build the project locally?
You marked that you could reproduce the issue locally. In this case please try to make it run locally first.
