### ISSUE TITLE
fortifyExecuteScan settings files

### ISSUE THREAD

**Issue by T1mey** [SAP/cloud-s4-sdk-pipeline#44]
Hi,

it seems the projectSettingsFile and globalSettingsFile parameter isn't recognized by the step fortifyExecuteScan.

![image](https://user-images.githubusercontent.com/10464878/89527317-6af4c780-d7e9-11ea-9712-195c7b2c7e9d.png)

Leads to debug output:

```
13:18:11  debug fortifyExecuteScan - Global settings file not provided via configuration.
13:18:11  debug fortifyExecuteScan - Project settings file not provided via configuration.
```
So our config is not recognized and it tries to downloaf from maven central (not reachable from our network).

File exists in the root of repository ... maybe not stashed / unstashed ?

**Comment by fwilhe** [comment]
Hi @T1mey 

just to avoid misunderstandings: The file does exist in the path `.pipeline/config.yml`, right? "root" might be a bit ambiguous.

Also, the `fortifyExecuteScan` section is in the `steps`, not in the `stages` section of your config file, right? Do other steps use the configuration?

Which Pipeline are you using? Which version?

Best,

Florian

**Comment by T1mey** [comment]
So with config file I meant 'settings.xml'... sorry for unclear description.
yes, the settings.xml file is recognizeg by the other steps e.g. mavenExecute and mtaBuild

fortifyExecuteScan and params are defined as step.

**Comment by fwilhe** [comment]
Hi @T1mey 

I think we need some more information. Ideally, it would be great if you could share a reproducible minimal example project (just to demonstrate this issue).

If this is not possible, the log of the fortify stage of this run would be helpful, of course with any confidential information redacted. If can't post it here, feel free to reach out via email.

Which version of the Pipeline are you using?

**Comment by stippi2** [comment]
During `fortifyExecuteScan` the maven settings (m2Path, projectSettingsFile, globalSettingsFile) are used only for generating the class-path which is then handed to the `sourceanalyzer` CLI tool.

I've tried to understand where this log-output comes from, and /maybe/ it is misleading. When the `fortifyExecuteScan` step starts, it needs to determine "artifact coordinates". For a maven project, this means evaluating the pom.xml file, which is also done with a maven execution. The log-output could come from this phase. But it is also possible that it actually doesn't work and the settings are really required, even for evaluating just groupId, artifactId, and version. In that case, a fix is needed in `fortifyExecuteScan` to pass on these parameters also for pom evaluation.

Can you clarify and perhaps provide the complete log-output if possible up to the point where the snippet is from?

**Comment by stippi2** [comment]
I have opened [this PR](https://github.com/SAP/jenkins-library/pull/1895). Not sure if this already enough, or whether the options also need to be passed to sourceanalyzer somehow.

**Comment by stippi2** [comment]
I've created a branch in the [public repository of our pipeline library](https://github.com/SAP/cloud-s4-sdk-pipeline-lib/compare/fix-fortify-maven). To test whether the above change in the `fortifyExecuteScan` step fixes your issue, you could consume the branch "fix-fortify-maven". I.e. in the Jenkinsfile for your project, make the following change:

```diff
-String pipelineVersion = "v39"
+String pipelineVersion = "fix-fortify-maven"
```

Please let me know how this goes.

**Comment by T1mey** [comment]
Thanks a lot for provding this fix... Just want to give it a try, but it seems that something else might have been changed. 
There is a file requested from an external URL which is at the moment not accesible from our network.

![image](https://user-images.githubusercontent.com/10464878/89613255-1baea580-d882-11ea-9b0c-7b009eb857c1.png)

It might be a good idea to provide list to which external systems / URL's the pipeline is connecting.
This will cause all our pipelines to fail if such a call is introduced.  --> breaking change

**Comment by stippi2** [comment]
No... that is a problem only with consuming a non-release branch of the repo where I needed to make the fix. Normally, the Groovy code in that library would load a release binary of the command line tool `piper`. The piper binary contains the new go-based portion of that library. The Groovy code realizes that no release is available for "fix-fortify-maven", and wants to fall-back to building the binary itself. It fails while fetching dependencies.

I think we have to wait until my fix is on master. A binary for the master branch is always available shortly (i.e. without actual "release").

**Comment by T1mey** [comment]
Thanks for information... when does this in general happen ?

**Comment by stippi2** [comment]
The fix is on master now, and the new binary should be available already. I adjusted the branch [fix-fortify-maven](https://github.com/SAP/cloud-s4-sdk-pipeline-lib/compare/fix-fortify-maven) of our library. You could just retry it now.

**Comment by T1mey** [comment]
@stippi2  Can confirm that config is loaded now. 
Struggeling with some internal setup on getting projects from SSC., but that's no pipeline issue.

**Comment by stippi2** [comment]
Thanks for the update!

**Comment by fwilhe** [comment]
Thanks for letting us know. Closing this issue as the original issue is resolved.
