### ISSUE TITLE
How to disable taging to github in production deployment stage for every run

### ISSUE THREAD

**Issue by santhosh042** [SAP/cloud-s4-sdk-pipeline#49]
## Issue Description (Mandatory)

The pipeline is failing in the stage: production deployment
https://qmpspa.jaas-gcp.cloud.sap.corp/job/qm-pspa/job/master/294/console

have to stop this tags  from pipeline:
https://github.wdf.sap.corp/quality-management/supplier-issue-process/releases/tag/build_0.0.1-20201006060143%2Ba3b0726a7d65b2a1babcb1bdd2b09aa54f71cc7f

https://github.wdf.sap.corp/quality-management/supplier-issue-process/releases/tag/ms%2F0.0.1-20201005135659%2B9931281994d35a735a99af06cdbb292961b69c71

**Comment by stippi2** [comment]
If you use our issue template, we can help you faster, as it prevents the need to ask for more information.

The pipeline run you linked did not fail in the production deployment stage. What do you mean?

If you don't want the version tags, you can configure the step `artifactPrepareVersion`, here is a link to its [documentation](https://sap.github.io/jenkins-library/steps/artifactPrepareVersion/). You can set the parameter `versioningType` to the value `cloud_noTag`. Please make sure that you really don't need these tags.

Please let me know if this solves the issue, thanks!

**Comment by santhosh042** [comment]
Hi Stephan,

Thanks for the solution..  it worked.

BR, Santhosh
