### ISSUE TITLE
Issue in clone SDK pipeline lib

### ISSUE THREAD

**Issue by santhosh042** [SAP/cloud-s4-sdk-pipeline#53]
stderr: remote: Password authentication is not available for Git operations.
15:51:25  remote: You must use a personal access token or SSH key.

## Issue Description (Mandatory)
We are facing this issue while cloning the s4SDk pipeline_lib. we did not make change on our side. 

The pipeline is failing in the stage: PUT NAME OF THE STAGE HERE
init

## Log Output (Mandatory)
https://qmpspa.jaas-gcp.cloud.sap.corp/job/qm-pspa/job/deploy_issue/11/console

```
15:51:24  The recommended git tool is: NONE
15:51:24  No credentials specified
15:51:24  Cloning the remote Git repository
15:51:24  Cloning repository https://github.wdf.sap.corp/MA/cloud-s4-sdk-pipeline-extensions.git
15:51:24   > git init /jenkinsdata/qm-pspa/deploy_issue/workspace@2/s4hana_pipeline/extensions # timeout=10
15:51:24  Fetching upstream changes from https://github.wdf.sap.corp/MA/cloud-s4-sdk-pipeline-extensions.git
15:51:24   > git --version # timeout=10
15:51:24   > git --version # 'git version 2.11.0'
15:51:24   > git fetch --tags --progress -- https://github.wdf.sap.corp/MA/cloud-s4-sdk-pipeline-extensions.git +refs/heads/*:refs/remotes/origin/* # timeout=10
15:51:25  ERROR: Error cloning remote repo 'origin'
15:51:25  hudson.plugins.git.GitException: Command "git fetch --tags --progress -- https://github.wdf.sap.corp/MA/cloud-s4-sdk-pipeline-extensions.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
15:51:25  stdout: 
15:51:25  stderr: remote: Password authentication is not available for Git operations.
15:51:25  remote: You must use a personal access token or SSH key.
15:51:25  remote: See https://github.wdf.sap.corp/settings/tokens or https://github.wdf.sap.corp/settings/ssh
15:51:25  fatal: unable to access 'https://github.wdf.sap.corp/MA/cloud-s4-sdk-pipeline-extensions.git/': The requested URL returned error: 403
```

## Link to Jenkins Job (if it can be shared)
https://qmpspa.jaas-gcp.cloud.sap.corp/job/qm-pspa/job/master/303/console
https://qmpspa.jaas-gcp.cloud.sap.corp/blue/organizations/jenkins/qm-pspa/detail/deploy_issue/10/pipeline/

PLEASE PLACE THE LINK HERE

## Reproduce the Issue Locally (Mandatory)

In case a maven/npm command or similar failed:
* [ ] I tried to reproduce the issue locally
* [ ] I could reproduce the issue locally

## Search for existing solution beforehand (Mandatory)

* [* ] I searched for an existing solution on [StackOverflow](https://stackoverflow.com/questions/tagged/sap-cloud-sdk) and my question was not answered there
* [* ] I searched for a similar GitHub issue before and found none
* [ ] I checked the [pipeline configuration docs](https://github.com/SAP/cloud-s4-sdk-pipeline/blob/master/configuration.md) and [the general pipeline docs](https://github.com/SAP/cloud-s4-sdk-pipeline/tree/master/doc/pipeline) for an answer of my issue

***Please try the GitHub search, it works really well***

## Project Details (Mandatory)

* Link to GitHub repo: PLACE YOUR LINK HERE
* Project type, for example:
    * [ ] SDK Maven Archetype
    * [ ] MTA (which types of modules?)
    * [ ] JavaScript
    * [ ] None of the above (unsupported)

**Comment by stippi2** [comment]
The extensions are being checked out using the Project "Piper" step [piperLoadGlobalExtensions](https://sap.github.io/jenkins-library/steps/piperLoadGlobalExtensions/). The non-anonymous checkout is supported since v37 of the pipeline and documented in the [release notes](https://github.com/SAP/cloud-s4-sdk-pipeline/releases/tag/v37).

So at the place where you configure the extensions in your `.pipeline/config.yml`, add the parameter `globalExtensionsRepositoryCredentialsId`:

```diff
general:
  gitCredentialsId: 'qmpspa_user_token' #gitCredentialsIdTechnicalUser
  globalExtensionsRepository: 'https://github.wdf.sap.corp/MA/cloud-s4-sdk-pipeline-extensions.git'
  globalExtensionsVersion: 'v37'
+ globalExtensionsRepositoryCredentialsId: 'qmpspa_user_token'
```
