### ISSUE TITLE
Piper reports "'syntax error: unexpected newline" error during cumulas upload step

### ISSUE THREAD

**Issue by santhosh042** [SAP/cloud-s4-sdk-pipeline#54]
## Issue Description (Mandatory)

The pipeline is failing in the stage: Build and Test

PLEASE PLACE YOUR DESCRIPTION HERE

## Log Output (Mandatory)

```
./sap-piper sapCumulusUpload --version jenkins-qm-pspa-master-347-0.0.1-20201109095945+feed7e4f7a04e509a73c6c242fb2136ec9e93d39 --pipelineId 69ce8364-37ee-4bb9-b4c8-f394afd1ebad --filePattern '**/target/surefire-reports/*.xml' --stepResultType junit
15:44:59  ./sap-piper: line 7: syntax error: unexpected newline
```

## Link to Jenkins Job (if it can be shared)

https://qmpspa.jaas-gcp.cloud.sap.corp/blue/organizations/jenkins/qm-pspa/detail/master/346/pipeline

## Search for existing solution beforehand (Mandatory)

* [* ] I searched for an existing solution on [StackOverflow](https://stackoverflow.com/questions/tagged/sap-cloud-sdk) and my question was not answered there
* [*] I searched for a similar GitHub issue before and found none
* [ ] I checked the [pipeline configuration docs](https://github.com/SAP/cloud-s4-sdk-pipeline/blob/master/configuration.md) and [the general pipeline docs](https://github.com/SAP/cloud-s4-sdk-pipeline/tree/master/doc/pipeline) for an answer of my issue

***Please try the GitHub search, it works really well***

## Project Details (Mandatory)

* Link to GitHub repo:  https://github.wdf.sap.corp/quality-management/supplier-issue-process/blob/master/.pipeline/config.yml

**Comment by daniel-kurzynski** [comment]
As this is in SAP internal issue, could you please open an issue in the SAP internal repository.
