### ISSUE TITLE
401 error:  while running executePPMSwhitessourcecheck introduced suddenly without any change in code

### ISSUE THREAD

**Issue by santhosh042** [SAP/cloud-s4-sdk-pipeline#56]
## Issue Description (Mandatory)

Found the below error in cloud sdk pipeline. we are at version 40. and suddenly we are facing the below access issue.

The pipeline is failing in the stage: executewhitesource--> executePPMSwhitesourcecheck

PLEASE PLACE YOUR DESCRIPTION HERE

## Log Output (Mandatory)

```
13:32:57  java.lang.IllegalStateException: hudson.AbortException: Fail: the returned code 401 is not in the accepted range: [[100‥399]]
13:32:57  ***
13:32:57  
13:32:57  Further information:
13:32:57  * Documentation of library step executePPMSWhitesourceComplianceCheck: https://github.wdf.sap.corp/pages/ContinuousDelivery/piper-doc/steps/executePPMSWhitesourceComplianceCheck/
13:32:57  * Source code of library step executePPMSWhitesourceComplianceCheck: https://github.wdf.sap.corp/ContinuousDelivery/piper-library/blob/master/vars/executePPMSWhitesourceComplianceCheck.groovy
13:32:57  * Library documentation: https://github.wdf.sap.corp/pages/ContinuousDelivery/piper-doc/
13:32:57  * Library repository: https://github.wdf.sap.corp/ContinuousDelivery/piper-library/
13:32:57  
13:32:57  ----------------------------------------------------------
13:32:57  --- End library step of: executePPMSWhitesourceComplianceCheck ---
```

## Link to Jenkins Job (if it can be shared)
https://qmpspa.jaas-gcp.cloud.sap.corp/job/qm-pspa/job/master/

## Search for existing solution beforehand (Mandatory)

* [ ] I searched for an existing solution on [StackOverflow](https://stackoverflow.com/questions/tagged/sap-cloud-sdk) and my question was not answered there
* [ ] I searched for a similar GitHub issue before and found none
* [ ] I checked the [pipeline configuration docs](https://github.com/SAP/cloud-s4-sdk-pipeline/blob/master/configuration.md) and [the general pipeline docs](https://github.com/SAP/cloud-s4-sdk-pipeline/tree/master/doc/pipeline) for an answer of my issue

***Please try the GitHub search, it works really well***

## Project Details (Mandatory)

* Link to GitHub repo: https://github.wdf.sap.corp/quality-management/supplier-issue-process/blob/master/.pipeline/config.yml

**Comment by fwilhe** [comment]
This is a "unauthorized" response from the api. Please check the validity of your credentials. This is not related to anything in the pipeline code.
